### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/project-generator#11]
Add CONTRIBUTING.md
Must be integrated and adapt to repo names

**Comment by PeterBowman** [comment]
There is a standard [CONTRIBUTING.md](https://github.com/roboticslab-uc3m/.github/blob/aa546bcb1f00cacc4d6b3f0cd6581fb5b48de8d2/CONTRIBUTING.md) at https://github.com/roboticslab-uc3m/.github. If the project lacks its own copy of this file, it will be linked to and suggested anyway during the creation of a new issue. It is also referenced in the "Community" tab in project settings.

Closing as wontfix.
