### ISSUE TITLE
Flexibility for SCREAMING_SNAKE_CASE and kebab-case?

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/project-generator#14]
Thoughts about allowing flexibility (removing automation) from SCREAMING_SNAKE_CASE and kebab-case?
Use case:
- `ROBOTICSLAB_KINEMATICS_DYNAMICS` (CMake exposed)
- `kinematics-dynamics` (doxygen internal)

**Comment by jgvictores** [comment]
PD: Highly related to https://github.com/roboticslab-uc3m/best-practices/issues/5

**Comment by PeterBowman** [comment]
We are fine with having two different naming conventions, albeit in unrelated contexts, and after 4+ years this topic is not worth revisiting as of today.
