### ISSUE TITLE
Add basic testing infrastructure and .travis.yml

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/project-generator#16]
Not so sure about the "testing infrastructure" until we decide on the most appropriate way of installing/embedding gtest.

**Comment by jgvictores** [comment]
@PeterBowman Maybe we should also consider upgrading Travis CI to Trusty as you mentioned [here](https://github.com/roboticslab-uc3m/gait/issues/6#issuecomment-292308644)?

**Comment by PeterBowman** [comment]
@jgvictores it really depends on the project - should it require support on older platforms, I'd stick with the Precise environment (see below). Different projects will meet different requirements, so I'd leave this choice up to the developer. That said, I'm not against setting Trusty as the default which I believe will happen sooner or later - keep in mind that Precise will reach EOL in this month.

Let me underline that we don't want to upgrade the `.travis.yml` currently in use in this repo (yet). This is mainly intended to ensure that the oldest supported versions of CMake actually build with YCM. This issue aims at creating a separate stub `.travis.yml` to be copied by the main shell script to the newly generated project.

**Comment by PeterBowman** [comment]
https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming

**Comment by PeterBowman** [comment]
> This issue aims at creating a separate stub `.travis.yml` to be copied by the main shell script to the newly generated project.

Travis YAML template file added at https://github.com/roboticslab-uc3m/project-generator/commit/4ca65dc5b6658cb96ef84601e59873032f207132.

**Comment by PeterBowman** [comment]
> Not so sure about the "testing infrastructure" until we decide on the most appropriate way of installing/embedding gtest.

Already decided: https://github.com/roboticslab-uc3m/questions-and-answers/issues/41.

**Comment by PeterBowman** [comment]
...and basic unit test stub added at https://github.com/roboticslab-uc3m/project-generator/commit/e6b9faf4c933d59431762bbd43c620e35c17f4a2.
